version: '3.8'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: lalaland
    ports:
      - "3306:3306"
    volumes:
      - smartschoolwebapi_SmartSchoolDb:/var/lib/mysql

  smartschool:
    image: smartschool
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - mysql

volumes:
  smartschoolwebapi_SmartSchoolDb:
